version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/pull_image.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 60
      runas: ec2-user
